vim_plugin_task "vimslim", "https://github.com/bbommarito/vim-slim.git"
skip_vim_plugin "NERDTree"
vim_plugin_task "jade.vim", "https://github.com/vim-scripts/jade.vim.git"
vim_plugin_task "stylus.vim", "https://github.com/wavded/vim-stylus.git"
vim_plugin_task "less.vim", "https://github.com/vim-scripts/less.vim.git"
vim_plugin_task "Extradite", "https://github.com/int3/vim-extradite.git"
vim_plugin_task "fugitive", "https://github.com/vim-scripts/fugitive.vim.git"
vim_plugin_task "scss-syntax", "https://github.com/cakebaker/scss-syntax.vim.git"
vim_plugin_task "vim-haml", "https://github.com/tpope/vim-haml.git"
